version: '3.7'

services: 
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: UTC
    volumes:
      - "mysql-db:/var/lib/mysql"

  api:
    tty: true
    stdin_open: true
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    environment:
      API_DOMAIN: "localhost:$FRONT_PORT"
      BASE_URL: "http://localhost:$API_PORT"
    ports:
      - "$API_PORT:3000"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./api:/app"
    command: rails server -b 0.0.0.0

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$API_PORT"
    # コンテナで実行したいコマンド(CMD)
    command: yarn run dev
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api
volumes:
  mysql-db:
    driver: local